force-app/main/default/objects/mockit__mdt/mockit__mdt.object-meta.xml
<CustomObject>
    <label>mockit</label>
    <pluralLabel>mockits</pluralLabel>
</CustomObject>

force-app/main/default/objects/mockit__mdt/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/mockit__mdt/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/mockit__mdt/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200</fullName>
                <default>true</default>
                <label>200</label>
            </value>
            <value>
                <fullName>201</fullName>
            </value>
            <value>
                <fullName>202</fullName>
            </value>
            <value>
                <fullName>204</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>301</fullName>
            </value>
            <value>
                <fullName>302</fullName>
            </value>
            <value>
                <fullName>304</fullName>
            </value>
            <value>
                <fullName>400</fullName>
            </value>
            <value>
                <fullName>401</fullName>
            </value>
            <value>
                <fullName>403</fullName>
            </value>
            <value>
                <fullName>404</fullName>
            </value>
            <value>
                <fullName>405</fullName>
            </value>
            <value>
                <fullName>406</fullName>
            </value>
            <value>
                <fullName>409</fullName>
            </value>
            <value>
                <fullName>410</fullName>
            </value>
            <value>
                <fullName>412</fullName>
            </value>
            <value>
                <fullName>413</fullName>
            </value>
            <value>
                <fullName>414</fullName>
            </value>
            <value>
                <fullName>415</fullName>
            </value>
            <value>
                <fullName>417</fullName>
            </value>
            <value>
                <fullName>500</fullName>
            </value>
            <value>
                <fullName>503</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MockitResource.cls
@RestResource(urlMapping='/mockit/*')
global with sharing class MockitResource {

    private class MockitMatch {
        Integer statusCode;
        String responseJson;
    }

    @HttpGet
    global static void getMockit() {
        System.debug('mockit:GET');
        String uri = RestContext.request.requestURI;
        System.debug(uri);
        MockitMatch mockitMatch = MockitResource.findMatch('GET', uri);
        System.debug(mockitMatch);
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.statusCode = mockitMatch.statusCode;
        RestContext.response.responseBody = Blob.valueOf(mockitMatch.responseJson);
    }

    @HttpPost
    global static void postMockit() {
        String uri = RestContext.request.requestURI;
        MockitMatch mockitMatch = MockitResource.findMatch('POST', uri);
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.statusCode = mockitMatch.statusCode;
        RestContext.response.responseBody = Blob.valueOf(mockitMatch.responseJson);
    }

    @HttpPut
    global static void putMockit() {
        String uri = RestContext.request.requestURI;
        MockitMatch mockitMatch = MockitResource.findMatch('PUT', uri);
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.statusCode = mockitMatch.statusCode;
        RestContext.response.responseBody = Blob.valueOf(mockitMatch.responseJson);
    }

    @HttpDelete
    global static void deleteMockit() {
        String uri = RestContext.request.requestURI;
        MockitMatch mockitMatch = MockitResource.findMatch('DELETE', uri);
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.statusCode = mockitMatch.statusCode;
        RestContext.response.responseBody = Blob.valueOf(mockitMatch.responseJson);
    }

    private static MockitMatch findMatch(String method, String uri){
        MockitMatch mockitMatch = new MockitMatch();
        mockitMatch.statusCode=404;
        mockitMatch.responseJson='{"message":"path not found"}';
        String jsonResponse = null;
        try{
            for(mockit__mdt m: [select match__c,id,response__c,status_code__c from mockit__mdt where active__c=true and method__c=:method order by label]){
                Pattern uriPattern = Pattern.compile(m.match__c);
                Matcher uriMatcher = uriPattern.matcher(uri);
                if(uriMatcher.matches()){
                    mockitMatch.statusCode = Integer.valueOf(m.status_code__c);
                    mockitMatch.responseJson = m.response__c;
                    break;
                }
            }
        }
        catch(Exception e){
            System.debug('Unable to locate uri: '+uri+' method: '+method);
            mockitMatch.statusCode = 500;
            mockitMatch.responseJson = '{"message":"exception locating path"}';
        }
        return mockitMatch;
    }

}